/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-03-10 04:58:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1642957317488L));
    _jspx_dependants.put("jar:file:/C:/Last/final-project/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Last/final-project/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/views/admin/sidebar.jsp", Long.valueOf(1643208870248L));
    _jspx_dependants.put("/WEB-INF/views/admin/FAQ.jsp", Long.valueOf(1643189397083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    	.wrap{\r\n");
      out.write("    		width: 100vw;\r\n");
      out.write("    	}\r\n");
      out.write("        .body{\r\n");
      out.write("        	height: 100%; \r\n");
      out.write("            float : left;\r\n");
      out.write("            width : 85%;\r\n");
      out.write("            box-sizing : border-box;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        .content{\r\n");
      out.write("            width: 80%; \r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        .btn-success{\r\n");
      out.write("            background: rgba(214, 11, 11, 0.521);\r\n");
      out.write("            border-color: rgba(214, 11, 11, 0.521);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        #textBox{\r\n");
      out.write("        	width: 100%; \r\n");
      out.write("        	height: 40px; \r\n");
      out.write("        	\r\n");
      out.write("        	border-color:rgba(170, 143, 211, 0.473); \r\n");
      out.write("        	border-radius: 5px; font-size: 18px; \r\n");
      out.write("        	padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("         #textBox:focus{\r\n");
      out.write("         	outline:rgba(170, 143, 211, 0.473);\r\n");
      out.write("         	border-color:rgba(170, 143, 211, 0.8); \r\n");
      out.write("         }\r\n");
      out.write("        #textArea{\r\n");
      out.write("        	width: 100%; \r\n");
      out.write("        	\r\n");
      out.write("        	border-color:rgba(170, 143, 211, 0.473); \r\n");
      out.write("        	resize: none; \r\n");
      out.write("        	border-radius: 5px; \r\n");
      out.write("        	padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("         #textArea:focus{\r\n");
      out.write("         	outline:rgba(170, 143, 211, 0.473);\r\n");
      out.write("         	border-color:rgba(170, 143, 211, 0.8); \r\n");
      out.write("         }\r\n");
      out.write("       \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("    	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("        .sidebar{\r\n");
      out.write("            width: 15%;  \r\n");
      out.write("            height: 100vh; \r\n");
      out.write("            background: rgb(170, 143, 211);\r\n");
      out.write("            color:rgba(255, 255, 255, 0.733);\r\n");
      out.write("            float : left;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        .side-title:hover{\r\n");
      out.write("            background: rgb(139, 111, 184);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("             padding-left: 18px;\r\n");
      out.write("            padding-right: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .side-title{\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            padding-top: 18px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .side-body{\r\n");
      out.write("            padding-left: 18px;\r\n");
      out.write("            padding-right: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .side-profile{\r\n");
      out.write("        	width: 150px;\r\n");
      out.write("		    height: 150px; \r\n");
      out.write("		    border-radius: 70%;\r\n");
      out.write("		    overflow: hidden;\r\n");
      out.write("		    margin-bottom: 10px;\r\n");
      out.write("		    margin-top: 10px;\r\n");
      out.write("		    margin-left: 30px;\r\n");
      out.write("		    \r\n");
      out.write("        }\r\n");
      out.write("        .profile {\r\n");
      out.write("		    width: 100%;\r\n");
      out.write("		    height: 100%;\r\n");
      out.write("		    object-fit: cover;\r\n");
      out.write("		}\r\n");
      out.write("		.side-profile:hover {\r\n");
      out.write("        	cursor:pointer;\r\n");
      out.write("            color:rgb(170, 143, 211);\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <!-- Latest compiled and minified CSS -->\r\n");
      out.write(" <link rel=\"stylesheet\"\r\n");
      out.write(" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write(" <!-- jQuery library -->\r\n");
      out.write(" <script\r\n");
      out.write(" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <!-- Popper JS -->\r\n");
      out.write(" <script\r\n");
      out.write(" src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <!-- Latest compiled JavaScript -->\r\n");
      out.write(" <script\r\n");
      out.write(" src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("        #notice_btn{\r\n");
      out.write("        	background-color: rgb(180, 143, 211);\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            position:fixed; right:30px; bottom:30px;\r\n");
      out.write("            box-shadow: 1px 1px 2px 3px rgb(219, 218, 218);\r\n");
      out.write("            width:100px;\r\n");
      out.write("            height:50px;\r\n");
      out.write("          \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #notice_post{\r\n");
      out.write("         	position: absolute;\r\n");
      out.write("         	z-index: 9999;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            height: 600px;\r\n");
      out.write("            position:fixed; right:30px; bottom:30px;\r\n");
      out.write("            box-shadow: 1px 1px 2px 3px rgb(219, 218, 218);\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #notice_header{\r\n");
      out.write("            border-top-left-radius: 10px;\r\n");
      out.write("            border-top-right-radius: 10px;\r\n");
      out.write("            height: 25%;\r\n");
      out.write("            background-color:rgb(170, 143, 211);\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #notice_body{\r\n");
      out.write("            border-bottom-left-radius: 10px;\r\n");
      out.write("            border-bottom-right-radius: 10px;\r\n");
      out.write("            height: 80%;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #notice_search{\r\n");
      out.write("            background-color: rgb(170, 143, 211);\r\n");
      out.write("            height: 10px;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        a {text-decoration: none; color: black;}\r\n");
      out.write("        a:hover {color: rgb(121, 42, 115);}\r\n");
      out.write("\r\n");
      out.write("        #search_btn{\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            border-color: transparent;\r\n");
      out.write("            font-weight : bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("            height : 30px;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        #notice_tb tbody tr td{\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("            font-size:15px;\r\n");
      out.write("        }\r\n");
      out.write("        #notice_tb tbody tr:hover {\r\n");
      out.write("        	cursor:pointer;\r\n");
      out.write("            color:rgb(170, 143, 211);\r\n");
      out.write("        }\r\n");
      out.write("        #notice_tb tbody tr td:first-child{\r\n");
      out.write("        	visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("	    width: 8px;\r\n");
      out.write("	    height: 8px;\r\n");
      out.write("	    background: #ffffff;\r\n");
      out.write("	  }\r\n");
      out.write("  	::-webkit-scrollbar-thumb {\r\n");
      out.write("	    border-radius: 3.5px;\r\n");
      out.write("	    background-color: #ced4da;\r\n");
      out.write("	\r\n");
      out.write("	    &:hover {\r\n");
      out.write("	      background-color: #adb5bd;\r\n");
      out.write("	    }\r\n");
      out.write("	 ::-webkit-scrollbar-track {\r\n");
      out.write("	    background: #ffffff;\r\n");
      out.write("	  }\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <button type=\"button\" class=\"btn\" id=\"notice_btn\" style=\"color: white; z-index:99999 \">\r\n");
      out.write("	        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-question-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	  <path fill-rule=\"evenodd\" d=\"M4.475 5.458c-.284 0-.514-.237-.47-.517C4.28 3.24 5.576 2 7.825 2c2.25 0 3.767 1.36 3.767 3.215 0 1.344-.665 2.288-1.79 2.973-1.1.659-1.414 1.118-1.414 2.01v.03a.5.5 0 0 1-.5.5h-.77a.5.5 0 0 1-.5-.495l-.003-.2c-.043-1.221.477-2.001 1.645-2.712 1.03-.632 1.397-1.135 1.397-2.028 0-.979-.758-1.698-1.926-1.698-1.009 0-1.71.529-1.938 1.402-.066.254-.278.461-.54.461h-.777ZM7.496 14c.622 0 1.095-.474 1.095-1.09 0-.618-.473-1.092-1.095-1.092-.606 0-1.087.474-1.087 1.091S6.89 14 7.496 14Z\"/>\r\n");
      out.write("	</svg>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"notice_post\">\r\n");
      out.write("        <div id=\"notice_header\">\r\n");
      out.write("            <button id=\"close\" style=\"float: right; margin-top: 20px; margin-right: 20px; background-color: transparent; border:transparent; color:white;\">\r\n");
      out.write("            	<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-x\" viewBox=\"0 0 16 16\">\r\n");
      out.write("				  <path d=\"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z\"/>\r\n");
      out.write("				</svg>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"back\" style=\"float: left; margin-top: 20px; margin-left: 20px;  background-color: transparent; border:transparent; color:white;\">\r\n");
      out.write("            	<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-arrow-left\" viewBox=\"0 0 16 16\">\r\n");
      out.write("				  <path fill-rule=\"evenodd\" d=\"M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z\"/>\r\n");
      out.write("				</svg>\r\n");
      out.write("            </button>\r\n");
      out.write("            <p align=\"center\" style=\"padding:15px 15px 15px 15px; color: white; font-size:23px;\">FAQ</p>\r\n");
      out.write("            \r\n");
      out.write("            <form name=\"search-form\">\r\n");
      out.write("	            <div id=\"notice_search\" align=\"center\">\r\n");
      out.write("	                    <input type=\"text\" name=\"keyword\" placeholder=\"내용 검색\" style=\"width: 80%; height:50px;\">\r\n");
      out.write("	                    <button type=\"button\" onclick=\"getSearchList()\"  id=\"search_btn\">\r\n");
      out.write("	                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                        <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\"/>\r\n");
      out.write("	                    </svg></button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("			\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"notice_body\" style=\"padding: 25px;  \">\r\n");
      out.write("            <div style=\"height: 90%; width: 100%; overflow:auto;\">\r\n");
      out.write("	           \r\n");
      out.write("	                <table id=\"notice_tb\" >\r\n");
      out.write("	                	<tbody>\r\n");
      out.write("	                		<tr></tr>\r\n");
      out.write("	                	</tbody>\r\n");
      out.write("	                </table>\r\n");
      out.write("                \r\n");
      out.write("                 \r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"text-align: right; height: 10%; width: 100%; background-color:white; \">\r\n");
      out.write("	                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-telephone-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                    <path fill-rule=\"evenodd\" d=\"M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z\"/>\r\n");
      out.write("	                </svg> 02-1234-0000 &nbsp;&nbsp;\r\n");
      out.write("	              \r\n");
      out.write("	         </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        $('#notice_post').hide();\r\n");
      out.write("        var box = $('#back');\r\n");
      out.write("        box.css('visibility', 'hidden'); \r\n");
      out.write("		\r\n");
      out.write("        $('#notice_btn').click(function(){\r\n");
      out.write("            $('#notice_btn').hide();\r\n");
      out.write("            $('#notice_post').show();\r\n");
      out.write("            getSearchList();\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        $('#close').click(function(){\r\n");
      out.write("            $('#notice_post').hide();\r\n");
      out.write("            $('#notice_btn').show();\r\n");
      out.write("            \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $('#back').click(function(){\r\n");
      out.write("        	getSearchList();\r\n");
      out.write("        	$(\"#notice_search\").show();\r\n");
      out.write("        	\r\n");
      out.write("	        var search3 = $('#notice_header');\r\n");
      out.write("	        search3.css('height', '25%').trigger(\"create\"); \r\n");
      out.write("	        var search2 = $('#notice_body');\r\n");
      out.write("	        search2.css('height', '75%').trigger(\"create\"); \r\n");
      out.write("	        var search3 = $('#back');\r\n");
      out.write("	        search3.css('visibility', 'hidden').trigger(\"create\"); \r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("    function getSearchList(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/faq/faq.do\",\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				data : $(\"form[name=search-form]\").serialize(),\r\n");
      out.write("				success : function(result) {\r\n");
      out.write("					\r\n");
      out.write("					var str = \"\";\r\n");
      out.write("					\r\n");
      out.write("					for(var i = 0; i < result.length; i++) {\r\n");
      out.write("						str += \"<tr>\"\r\n");
      out.write("							 		+ \"<td>\"+ result[i].noticeNo + \"</td>\" \r\n");
      out.write("							 		+ \"<td>\" + parseInt(i+1) +\".</td>\"\r\n");
      out.write("							 		+ \"<td>\" + result[i].noticeTitle + \"</td>\"\r\n");
      out.write("							 + \"</tr>\";\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					$(\"#notice_tb > tbody\").html(str);\r\n");
      out.write("					$(function() {\r\n");
      out.write("					    $(\"#notice_tb tbody tr\").css(\"font-size\", \"10px\").trigger(\"create\"); \r\n");
      out.write("					    });\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					console.log(\"ajax 통신 실패!\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("    };\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(function(FAQ_ajax) {\r\n");
      out.write("			$(document).on('click','#notice_tb tbody tr',function() {\r\n");
      out.write("				\r\n");
      out.write("				var nno = $(this).children().eq(0).text();\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/faq/faq.de\",\r\n");
      out.write("					type : \"get\",\r\n");
      out.write("					data : { nno : nno },\r\n");
      out.write("					success : function(result) {\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						var str = \"\";\r\n");
      out.write("							str = \"<p>\" +\"[\"+ result.noticeType +\"]\" + result.noticeTitle + \"</p>\"+ \"<br>\"+\r\n");
      out.write("								\r\n");
      out.write("								  result.noticeContent;\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						$(\"#notice_tb > tbody\").html(str);\r\n");
      out.write("						\r\n");
      out.write("						$(function() {\r\n");
      out.write("						    $(\"#notice_tb tbody p\").css(\"font-weight\", \"bold\").trigger(\"create\"); \r\n");
      out.write("						    });\r\n");
      out.write("						$(function() {\r\n");
      out.write("					        $(\"#notice_tb tbody p\").css(\"font-size\", \"12px\").trigger(\"create\"); \r\n");
      out.write("					    });\r\n");
      out.write("						$(function() {\r\n");
      out.write("					        $(\"#notice_search\").hide().trigger(\"create\"); \r\n");
      out.write("					        var search = $('#notice_header');\r\n");
      out.write("					        search.css('height', '10%').trigger(\"create\"); \r\n");
      out.write("					        var search2 = $('#notice_body');\r\n");
      out.write("					        search2.css('height', '90%').trigger(\"create\"); \r\n");
      out.write("					        \r\n");
      out.write("					    });\r\n");
      out.write("						\r\n");
      out.write("						$(function() {\r\n");
      out.write("							var box = $('#back');\r\n");
      out.write("					        box.css('visibility', 'visible').trigger(\"create\"); \r\n");
      out.write("					    });\r\n");
      out.write("					},\r\n");
      out.write("					error : function() {\r\n");
      out.write("						console.log(\"ㅜㅜ\");\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		 \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" 			\r\n");
      out.write(" 			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <div class=\"sidebar\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"side-body\">\r\n");
      out.write("               \r\n");
      out.write("                    <div class=\"side-profile\"  >\r\n");
      out.write("                    	<img class=\"profile\" src=\"../resources/images/loginLogo.jpg\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                	\r\n");
      out.write("                    <hr color=\"white\">\r\n");
      out.write("                    <div class=\"side-title\" id=\"Home\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-house-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path fill-rule=\"evenodd\" d=\"m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z\"/>\r\n");
      out.write("                            <path fill-rule=\"evenodd\" d=\"M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z\"/>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                        Home</div> \r\n");
      out.write("                    <div class=\"side-title\" id=\"Customers\">\r\n");
      out.write("                         <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-person-lines-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path d=\"M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z\"/>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                         Customers</div>\r\n");
      out.write("                    <div class=\"side-title\" id=\"Notice\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-megaphone-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path d=\"M13 2.5a1.5 1.5 0 0 1 3 0v11a1.5 1.5 0 0 1-3 0v-11zm-1 .724c-2.067.95-4.539 1.481-7 1.656v6.237a25.222 25.222 0 0 1 1.088.085c2.053.204 4.038.668 5.912 1.56V3.224zm-8 7.841V4.934c-.68.027-1.399.043-2.008.053A2.02 2.02 0 0 0 0 7v2c0 1.106.896 1.996 1.994 2.009a68.14 68.14 0 0 1 .496.008 64 64 0 0 1 1.51.048zm1.39 1.081c.285.021.569.047.85.078l.253 1.69a1 1 0 0 1-.983 1.187h-.548a1 1 0 0 1-.916-.599l-1.314-2.48a65.81 65.81 0 0 1 1.692.064c.327.017.65.037.966.06z\"/>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                        Notice</div>\r\n");
      out.write("                        <div class=\"side-title\" id=\"Data\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-bar-chart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("						  <path d=\"M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z\"/>\r\n");
      out.write("						</svg>\r\n");
      out.write("                        Data</div> \r\n");
      out.write("                        <div class=\"side-title\" id=\"Message\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-envelope\" viewBox=\"0 0 16 16\">\r\n");
      out.write("						  <path d=\"M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z\"/>\r\n");
      out.write("						</svg>\r\n");
      out.write("                        Message  </div> \r\n");
      out.write("                        \r\n");
      out.write("                    <div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function (){\r\n");
      out.write("            $(\".profile\").click(function(){\r\n");
      out.write("                location.href=\"../");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#Home\").click(function(){\r\n");
      out.write("                location.href=\"admin.do\";\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#Customers\").click(function(){\r\n");
      out.write("                location.href=\"customer.do\";\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#Notice\").click(function(){\r\n");
      out.write("                location.href=\"notice.do\";\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#Message\").click(function(){\r\n");
      out.write("                location.href=\"message.do\";\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#Data\").click(function(){\r\n");
      out.write("                location.href=\"data.do\";\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("    function fnChkByte(obj, maxByte)\r\n");
      out.write("    {\r\n");
      out.write("        var str = obj.value;\r\n");
      out.write("        var str_len = str.length;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var rbyte = 0;\r\n");
      out.write("        var rlen = 0;\r\n");
      out.write("        var one_char = \"\";\r\n");
      out.write("        var str2 = \"\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        for(var i=0; i<str_len; i++)\r\n");
      out.write("        {\r\n");
      out.write("            one_char = str.charAt(i);\r\n");
      out.write("            if(escape(one_char).length > 4) {\r\n");
      out.write("                rbyte += 2;                                         //한글2Byte\r\n");
      out.write("            }else{\r\n");
      out.write("                rbyte++;                                            //영문 등 나머지 1Byte\r\n");
      out.write("            }\r\n");
      out.write("            if(rbyte <= maxByte){\r\n");
      out.write("                rlen = i+1;                                          //return할 문자열 갯수\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         if(rbyte > maxByte)\r\n");
      out.write("         {\r\n");
      out.write("            // alert(\"한글 \"+(maxByte/2)+\"자 / 영문 \"+maxByte+\"자를 초과 입력할 수 없습니다.\");\r\n");
      out.write("            alert(\"메세지는 최대 \" + maxByte + \"byte를 초과할 수 없습니다.\")\r\n");
      out.write("            str2 = str.substr(0,rlen);                                  //문자열 자르기\r\n");
      out.write("            obj.value = str2;\r\n");
      out.write("            fnChkByte(obj, maxByte);\r\n");
      out.write("         }\r\n");
      out.write("         else\r\n");
      out.write("         {\r\n");
      out.write("            document.getElementById('byteInfo').innerText = rbyte;\r\n");
      out.write("         }\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        <div class=\"body\">\r\n");
      out.write("            \r\n");
      out.write("            <form action=\"notice.ad\" method=\"post\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                        <span style=\"font-size: 35px; font-weight: bold;\">Add Notice</span>\r\n");
      out.write("	                        <div style=\"float:right;\">\r\n");
      out.write("		                        <select style=\"width:95px; height:30px;\" name=\"noticeType\">\r\n");
      out.write("		                        	<option>공지사항</option>\r\n");
      out.write("		                        	<option>FAQ</option>\r\n");
      out.write("		                        </select>\r\n");
      out.write("		                        \r\n");
      out.write("		                    </div>\r\n");
      out.write("                        <input type=\"text\" id=\"textBox\" placeholder=\"제목\" name=\"noticeTitle\"><br><br>\r\n");
      out.write("                        <textarea cols=\"147\" rows=\"20\" id=\"textArea\"  placeholder=\"내용\" name=\"noticeContent\"></textarea>\r\n");
      out.write("                   <br><br>\r\n");
      out.write("                   <div align=\"center\">\r\n");
      out.write("                   <button type=\"submit\" class=\"btn\" style=\"border-bottom-left-radius:20px;border-top-left-radius:20px; color:white; width:100px; height:40px; background: rgba(170, 143, 211,0.3666);\">등록하기</button>\r\n");
      out.write("                   <button type=\"button\" class=\"btn\" style=\"border-bottom-right-radius:20px;border-top-right-radius:20px; color:white; width:100px; height:40px; background: rgba(170, 143, 211,0.3666);\" onclick=\"history.back();\">뒤로가기</button>\r\n");
      out.write("                   \r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/admin/sidebar.jsp(66,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty alertMsg }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<script>\r\n");
          out.write("					var msg = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ alertMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\r\n");
          out.write("					alert(msg);\r\n");
          out.write("				</script>\r\n");
          out.write("				");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/admin/sidebar.jsp(71,4) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("alertMsg");
      // /WEB-INF/views/admin/sidebar.jsp(71,4) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
