/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-24 04:33:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class changePhone_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1642957317488L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/myPageSidebar.jsp", Long.valueOf(1642756614000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/footer.jsp", Long.valueOf(1642989546860L));
    _jspx_dependants.put("jar:file:/C:/Last/final-project/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	#content {\r\n");
      out.write("        height: 1000px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #update {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("        margin-left: 50px;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #update li {\r\n");
      out.write("    	cursor : pointer;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"header\"></div>\r\n");
      out.write("	<div id=\"includedContent\"></div>\r\n");
      out.write("	<div id=\"content\">\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
 String contextPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    #content {\r\n");
      out.write("    	height:1000px;\r\n");
      out.write("    }\r\n");
      out.write("    #content>div {\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu {\r\n");
      out.write("        width: 15%;\r\n");
      out.write("        height: 420px;\r\n");
      out.write("        background-color: rgb(170, 143, 211);\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu>ul {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu li {\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu li:hover {\r\n");
      out.write("        background-color: hotpink;\r\n");
      out.write("        cursor : pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("	<div id=\"menu\">\r\n");
      out.write("                <ul class=\"list-group\">\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"myPage();\">개인정보수정</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"tHistory();\">거래내역</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"zzimList();\">관심목록</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"teacherAdd();\">선생신청</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"myProfile();\">내 프로필</li>\r\n");
      out.write("                    <li class=\"list-group-item\" data-toggle=\"modal\" data-target=\"#myModal\">계정탈퇴</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("  \r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">정말로 탈퇴 하시겠습니까?</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <!-- Modal body -->\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("         	계정 탈퇴 시 모든 개인정보가 삭제되며\r\n");
      out.write("		구매하신 캐시는 환불되지 않아요\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-danger\" onclick=\"exit()\">탈퇴</button>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	function myPage() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/mypage.do\";\r\n");
      out.write("	}\r\n");
      out.write("	function tHistory() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/thistory.do?currentPage=1\";\r\n");
      out.write("	}\r\n");
      out.write("	function zzimList() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/zzimlist.do?currentPage=1\";\r\n");
      out.write("	}\r\n");
      out.write("	function teacherAdd() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/teacherAdd.do\";\r\n");
      out.write("	}\r\n");
      out.write("	function myProfile() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/myProfile.do\";\r\n");
      out.write("	}\r\n");
      out.write("	function exit() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/exit.do\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            <div id=\"update\">\r\n");
      out.write("            <h2>전화번호 수정</h2>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <form action=\"changePhone.do\" method=\"post\">\r\n");
      out.write("            <h4 style=\"color:gray\">전화번호</h4>\r\n");
      out.write("            <div><input type=\"text\" name=\"memberPhone\" style=\"width:50%\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.memberPhone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required></div>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <div align=\"center\">\r\n");
      out.write("                <button class=\"btn btn-secondary\">취소</button>\r\n");
      out.write("                <button class=\"btn btn-primary\" type=\"submit\" style=\"background-color:rgb(170, 143, 211); border: 1px soild rgb(170, 143, 211);\">수정 완료</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>재능판다</title>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 웹 폰트-->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Karla&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("		*:not(i) {\r\n");
      out.write("			font-family: 'Karla', sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<footer class=\"footer-07\" style=\"background-color: rgb(170, 143, 211);\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-12 text-center\">\r\n");
      out.write("					<h2 class=\"footer-heading\" style=\"margin-top:50px;\"><a href=\"#\" class=\"logo\" style=\"text-decoration :none\">TalentsellerPanda.com</a></h2>\r\n");
      out.write("					<p class=\"menu\">\r\n");
      out.write("						<a href=\"#\">재능판다</a>&nbsp;&nbsp;\r\n");
      out.write("						<a href=\"#\">1대1문의</a>&nbsp;&nbsp;\r\n");
      out.write("						<a href=\"#\">FAQ</a>&nbsp;&nbsp;\r\n");
      out.write("						<a href=\"#\">공지사항</a>&nbsp;&nbsp;\r\n");
      out.write("					</p>\r\n");
      out.write("					<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("		  <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Twitter\"><span class=\"ion-logo-twitter\"></span></a></li>\r\n");
      out.write("		  <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Facebook\"><span class=\"ion-logo-facebook\"></span></a></li>\r\n");
      out.write("		  <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Instagram\"><span class=\"ion-logo-instagram\"></span></a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-5\">\r\n");
      out.write("				<div class=\"col-md-12 text-center\">\r\n");
      out.write("					<p class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("				  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"ion-ios-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\"  style=\"color: transparent;\">Colorlib.com</a>\r\n");
      out.write("				  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\"\r\n");
      out.write("				stroke=\"#F96D00\" />\r\n");
      out.write("		</svg></div>\r\n");
      out.write("	<script src=\"../resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/c8ea39d107.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
