/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-24 08:36:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>재능판다</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<!-- 웹 폰트-->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Karla&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("*:not(i) {\r\n");
      out.write("	font-family: 'Karla', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar-logo>img {\r\n");
      out.write("	padding-top: 0px;\r\n");
      out.write("	padding-bottom: 18px;\r\n");
      out.write("	width: 110px;\r\n");
      out.write("	height: 110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divider-text {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divider-text span {\r\n");
      out.write("	padding: 7px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divider-text:after {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("	top: 55%;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-button {\r\n");
      out.write("	color: rgb(170, 143, 211);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-button:hover, .form-button:focus, .form-button:active,\r\n");
      out.write("	.form-button.active, .form-button:active:focus, .form-button:active:hover,\r\n");
      out.write("	.form-button.active:hover, .form-button.active:focus {\r\n");
      out.write("	border-color: lightsalmon;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\"\r\n");
      out.write("		style=\"margin: auto; margin-top: 200px; margin-bottom: 100px;\">\r\n");
      out.write("		<div class=\"card bg-light\">\r\n");
      out.write("			<article class=\"card-body mx-auto\" style=\"max-width: 400px;\">\r\n");
      out.write("				<h4 class=\"card-title mt-3 text-center\">회원가입</h4>\r\n");
      out.write("				<p class=\"text-center\">재능판다에 오신걸 환영합니다.</p>\r\n");
      out.write("				<form method=\"post\" action=\"join.do\" id=\"joinForm\" name=\"joinForm\"\r\n");
      out.write("					onsubmit=\"return checkInput();\">\r\n");
      out.write("					<div class=\"form-group input-group\">\r\n");
      out.write("						<div class=\"input-group-prepend\">\r\n");
      out.write("							<span class=\"input-group-text\"> <i class=\"fa fa-user\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<input name=\"memberId\" id=\"memberId\" class=\"form-control\"\r\n");
      out.write("							placeholder=\"아이디\" type=\"text\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group input-group\">\r\n");
      out.write("						<div class=\"input-group-prepend\">\r\n");
      out.write("							<span class=\"input-group-text\"> <i class=\"fa fa-lock\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<input class=\"form-control\" id=\"memberPwd\" name=\"memberPwd\"\r\n");
      out.write("							placeholder=\"비밀번호 입력\" type=\"password\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- form-group// -->\r\n");
      out.write("					<div class=\"form-group input-group\">\r\n");
      out.write("						<div class=\"input-group-prepend\">\r\n");
      out.write("							<span class=\"input-group-text\"> <i class=\"fa fa-lock\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<input class=\"form-control\" id=\"pwdCheck\" name=\"pwdCheck\"\r\n");
      out.write("							placeholder=\"비밀번호 확인\" type=\"password\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- form-group// -->\r\n");
      out.write("					<div class=\"form-group input-group\">\r\n");
      out.write("						<div class=\"input-group-prepend\">\r\n");
      out.write("							<span class=\"input-group-text\"> <i class=\"fa fa-user\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<input name=\"memberName\" id=\"memberName\" class=\"form-control\"\r\n");
      out.write("							placeholder=\"이름(실명) 입력\" type=\"text\"> <br>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group input-group\">\r\n");
      out.write("						<div class=\"input-group-prepend\">\r\n");
      out.write("							<span class=\"input-group-text\"> <i class=\"fa fa-user\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<input name=\"memberNick\" id=\"memberNick\" class=\"form-control\"\r\n");
      out.write("							placeholder=\"닉네임(별칭)\" type=\"text\">\r\n");
      out.write("						<button id=\"nickCheck\" type=\"button\" onclick=\"fn_nickCheck();\" value=\"N\">중복체크</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- form-group// -->\r\n");
      out.write("					<div class=\"form-group input-group\">\r\n");
      out.write("						<div class=\"input-group-prepend\">\r\n");
      out.write("							<span class=\"input-group-text\"> <i class=\"fa fa-phone\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<input id=\"memberPhone\" name=\"memberPhone\" class=\"form-control\"\r\n");
      out.write("							placeholder=\"휴대폰 번호('-' 제외)\" type=\"text\">\r\n");
      out.write("						<button id=\"phoneCheck\" type=\"button\" onclick=\"fn_phoneCheck();\" value=\"N\">중복체크</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- form-group// -->\r\n");
      out.write("					<div class=\"form-group input-group\">\r\n");
      out.write("						<div class=\"input-group-prepend\">\r\n");
      out.write("							<span class=\"input-group-text\"> <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<input name=\"memberEmail\" id=\"memberEmail\" class=\"form-control\"\r\n");
      out.write("							placeholder=\"이메일주소\" type=\"email\">\r\n");
      out.write("						<button id=\"emailCheck\" type=\"button\" onclick=\"fn_emailCheck();\"\r\n");
      out.write("							value=\"N\">중복체크</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- form-group// -->\r\n");
      out.write("					<!-- form-group// -->\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<input type=\"text\" id=\"sample2_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("						<input type=\"text\" id=\"address\" name=\"address\" placeholder=\"주소\"><br>\r\n");
      out.write("						<input type=\"text\" id=\"detailAddress\" name=\"detailAddress\" required\r\n");
      out.write("							placeholder=\"상세주소\"> <input type=\"button\" id=\"postnumBnt\"\r\n");
      out.write("							onclick=\"sample2_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<button type=\"submit\" id=\"submit\"\r\n");
      out.write("							class=\"btn btn-primary btn-block\"\r\n");
      out.write("							style=\"color: white; background-color: rgb(170, 143, 211); border: 1px solid transparent;\">\r\n");
      out.write("							회원가입</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- form-group// -->\r\n");
      out.write("					<p class=\"text-center\" style=\"color: black;\">\r\n");
      out.write("						<strong>이미 가입하셨나요?</strong> <a\r\n");
      out.write("							href=\"");
      out.print(contextPath);
      out.write("/member/login.do\" class=\"form-button\">로그인\r\n");
      out.write("							하기</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</form>\r\n");
      out.write("			</article>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- card.// -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--container end.//-->\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("		integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<div id=\"layer\"\r\n");
      out.write("		style=\"display: none; position: fixed; overflow: hidden; z-index: 1; -webkit-overflow-scrolling: touch;\">\r\n");
      out.write("		<img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\"\r\n");
      out.write("			id=\"btnCloseLayer\"\r\n");
      out.write("			style=\"cursor: pointer; position: absolute; right: -3px; top: -3px; z-index: 1\"\r\n");
      out.write("			onclick=\"closeDaumPostcode()\" alt=\"닫기 버튼\">\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		// 우편번호 찾기 화면을 넣을 element\r\n");
      out.write("		var element_layer = document.getElementById('layer');\r\n");
      out.write("\r\n");
      out.write("		function closeDaumPostcode() {\r\n");
      out.write("			// iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("			element_layer.style.display = 'none';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function sample2_execDaumPostcode() {\r\n");
      out.write("			new daum.Postcode(\r\n");
      out.write("					{\r\n");
      out.write("						oncomplete : function(data) {\r\n");
      out.write("							// 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("							// 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("							// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("							var addr = ''; // 주소 변수\r\n");
      out.write("							var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("							//사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("							if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("								addr = data.roadAddress;\r\n");
      out.write("							} else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("								addr = data.jibunAddress;\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("							// 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("							if (data.userSelectedType === 'R') {\r\n");
      out.write("								// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("								// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("								if (data.bname !== ''\r\n");
      out.write("										&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("									extraAddr += data.bname;\r\n");
      out.write("								}\r\n");
      out.write("								// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("								if (data.buildingName !== ''\r\n");
      out.write("										&& data.apartment === 'Y') {\r\n");
      out.write("									extraAddr += (extraAddr !== '' ? ', '\r\n");
      out.write("											+ data.buildingName\r\n");
      out.write("											: data.buildingName);\r\n");
      out.write("								}\r\n");
      out.write("								// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("								if (extraAddr !== '') {\r\n");
      out.write("									extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("								}\r\n");
      out.write("								// 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("								addr += extraAddr;\r\n");
      out.write("							} else {\r\n");
      out.write("								addr += ' ';\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("							// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("							document.getElementById('sample2_postcode').value = data.zonecode;\r\n");
      out.write("							document.getElementById(\"address\").value = addr;\r\n");
      out.write("							// 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("							document.getElementById(\"detailAddress\").focus();\r\n");
      out.write("							console.log(\"detailAddress : \" + detailAddress);\r\n");
      out.write("							// iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("							// (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)\r\n");
      out.write("							element_layer.style.display = 'none';\r\n");
      out.write("						},\r\n");
      out.write("						width : '100%',\r\n");
      out.write("						height : '100%',\r\n");
      out.write("						maxSuggestItems : 5\r\n");
      out.write("					}).embed(element_layer);\r\n");
      out.write("\r\n");
      out.write("			// iframe을 넣은 element를 보이게 한다.\r\n");
      out.write("			element_layer.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("			// iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.\r\n");
      out.write("			initLayerPosition();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는\r\n");
      out.write("		// resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,\r\n");
      out.write("		// 직접 element_layer의 top,left값을 수정해 주시면 됩니다.\r\n");
      out.write("		function initLayerPosition() {\r\n");
      out.write("			var width = 300; //우편번호서비스가 들어갈 element의 width\r\n");
      out.write("			var height = 400; //우편번호서비스가 들어갈 element의 height\r\n");
      out.write("			var borderWidth = 5; //샘플에서 사용하는 border의 두께\r\n");
      out.write("\r\n");
      out.write("			// 위에서 선언한 값들을 실제 element에 넣는다.\r\n");
      out.write("			element_layer.style.width = width + 'px';\r\n");
      out.write("			element_layer.style.height = height + 'px';\r\n");
      out.write("			element_layer.style.border = borderWidth + 'px solid';\r\n");
      out.write("			// 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.\r\n");
      out.write("			element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width) / 2 - borderWidth)\r\n");
      out.write("					+ 'px';\r\n");
      out.write("			element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height) / 2 - borderWidth)\r\n");
      out.write("					+ 'px';\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function checkInput() {\r\n");
      out.write("			\r\n");
      out.write("			if (document.joinForm.memberId.value == \"\"){\r\n");
      out.write("				alert(\"아이디를 입력해 주세요.\");\r\n");
      out.write("				document.joinForm.memberId.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.memberPwd.value == \"\"){\r\n");
      out.write("				alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("				document.joinForm.memberPwd.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.pwdCheck.value == \"\"){\r\n");
      out.write("				alert(\"비밀번호확인을 입력해주세요.\");\r\n");
      out.write("				document.joinForm.pwdCheck.focus();\r\n");
      out.write("				return false;	\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.memberName.value == \"\") {\r\n");
      out.write("				alert(\"이름을 입력해주세요\");\r\n");
      out.write("				document.joinForm.memberName.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.memberNick.value == \"\") {\r\n");
      out.write("				alert(\"닉네임을 입력해 주세요\");\r\n");
      out.write("				document.joinForm.memberNick.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.memberPhone.value == \"\") {\r\n");
      out.write("				alert(\"휴대폰번호를 입력해 주세요\");\r\n");
      out.write("				document.joinForm.memberPhone.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.memberEmail.value == \"\") {\r\n");
      out.write("				alert(\"이메일을 입력해 주세요\");\r\n");
      out.write("				document.joinForm.memberEmail.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.address.value == \"\") {\r\n");
      out.write("				alert(\"우편번호 찾기를 진행 해주세요\");\r\n");
      out.write("				document.joinForm.address.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.nickCheck.value == \"N\") {\r\n");
      out.write("				alert(\"닉네임 중복체크를 해주세요\");\r\n");
      out.write("				document.joinForm.nickCheck.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.phoneCheck.value == \"N\") {\r\n");
      out.write("				alert(\"휴대폰 번호 중복체크를 해주세요\");\r\n");
      out.write("				document.joinForm.phoneCheck.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (document.joinForm.emailCheck.value == \"N\") {\r\n");
      out.write("				alert(\"이메일 중복체크를 해주세요\");\r\n");
      out.write("				document.joinForm.emailCheck.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			var regExp = /^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,25}$/;\r\n");
      out.write("			var pw = document.getElementById('memberPwd').value;\r\n");
      out.write("			if (!regExp.test(pw)) {\r\n");
      out.write("				alert(\"비밀번호 형식을 확인해주세요 (영 대소문자 숫자 8~15자리)\");\r\n");
      out.write("				document.getElementById('memberPwd').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			var pw_check = document.getElementById('pwdCheck').value;\r\n");
      out.write("			if (!regExp.test(pw_check)) {\r\n");
      out.write("				alert(\"비밀번호 확인 형식을 확인해주세요 (영 대소문자 숫자 8~15자리)\");\r\n");
      out.write("				document.getElementById('pwdCheck').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if (!(pw == pw_check)) {\r\n");
      out.write("				alert(\"비밀번호와 확인이 일치하지 않습니다.\");\r\n");
      out.write("				document.getElementById('pwdCheck').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			regExp = /^[가-힣]{2,}$/;\r\n");
      out.write("			var name = document.getElementById('memberName').value;\r\n");
      out.write("			if (!regExp.test(name)) {\r\n");
      out.write("				alert(\"이름을 확인해주세요\");\r\n");
      out.write("				document.getElementById('memberName').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			regExp = /^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$/;\r\n");
      out.write("			var phone = document.getElementById('memberPhone').value;\r\n");
      out.write("			if (!regExp.test(phone)) {\r\n");
      out.write("				alert(\"전화번호 형식을 확인해주세요(-제외)\");\r\n");
      out.write("				document.getElementById('memberPhone').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 중복 체크 버튼 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		function fn_emailCheck() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"/member/emailCheck.do\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"memberEmail\" : $(\"#memberEmail\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					if (data == 1) {\r\n");
      out.write("						alert(\"중복된 이메일입니다.\");\r\n");
      out.write("					} else if (data == 0) {\r\n");
      out.write("						$(\"#emailCheck\").attr(\"value\", \"Y\");\r\n");
      out.write("						alert(\"사용 가능한 이메일입니다.\")\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fn_nickCheck() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"/member/nickCheck.do\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"memberNick\" : $(\"#memberNick\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					if (data == 1) {\r\n");
      out.write("						alert(\"중복된 닉네임입니다.\");\r\n");
      out.write("					} else if (data == 0) {\r\n");
      out.write("						$(\"#nickCheck\").attr(\"value\", \"Y\");\r\n");
      out.write("						alert(\"사용 가능한 닉네임입니다.\")\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function fn_phoneCheck() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"/member/phoneCheck.do\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"memberPhone\" : $(\"#memberPhone\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					if (data == 1) {\r\n");
      out.write("						alert(\"중복된 휴대폰 번호입니다.\");\r\n");
      out.write("					} else if (data == 0) {\r\n");
      out.write("						$(\"#phoneCheck\").attr(\"value\", \"Y\");\r\n");
      out.write("						alert(\"사용 가능한 휴대폰 번호입니다.\")\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
