/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-26 08:38:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        html {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Text Align */\r\n");
      out.write("        .text-c {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-l {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-r {\r\n");
      out.write("            text-align: right\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-j {\r\n");
      out.write("            text-align: justify;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Text Color */\r\n");
      out.write("        .text-whitesmoke {\r\n");
      out.write("            color: black\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-darkyellow {\r\n");
      out.write("            color: rgb(170, 143, 211);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Lines */\r\n");
      out.write("\r\n");
      out.write("        .line-b {\r\n");
      out.write("            border-bottom: 1px solid rgb(170, 143, 211) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons */\r\n");
      out.write("        .button {\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-button {\r\n");
      out.write("            background-color: rgb(170, 143, 211);\r\n");
      out.write("            border-color: rgb(170, 143, 211);\r\n");
      out.write("            color: #e6e6e6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-button:hover,\r\n");
      out.write("        .form-button:focus,\r\n");
      out.write("        .form-button:active,\r\n");
      out.write("        .form-button.active,\r\n");
      out.write("        .form-button:active:focus,\r\n");
      out.write("        .form-button:active:hover,\r\n");
      out.write("        .form-button.active:hover,\r\n");
      out.write("        .form-button.active:focus {\r\n");
      out.write("            background-color: lightsalmon;\r\n");
      out.write("            border-color: lightsalmon;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-l {\r\n");
      out.write("            width: 100% !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Margins g(global) - l(left) - r(right) - t(top) - b(bottom) */\r\n");
      out.write("\r\n");
      out.write("        .margin-g {\r\n");
      out.write("            margin: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-g-sm {\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-g-md {\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-g-lg {\r\n");
      out.write("            margin: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-l {\r\n");
      out.write("            margin-left: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-l-sm {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-l-md {\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-l-lg {\r\n");
      out.write("            margin-left: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-r {\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-r-sm {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-r-md {\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-r-lg {\r\n");
      out.write("            margin-right: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-t {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-t-sm {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-t-md {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-t-lg {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-b {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-b-sm {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-b-md {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .margin-b-lg {\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Bootstrap Form Control Extension */\r\n");
      out.write("\r\n");
      out.write("        .form-control,\r\n");
      out.write("        .border-line {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            background-image: none;\r\n");
      out.write("            border: 1px solid rgb(170, 143, 211);\r\n");
      out.write("            border-radius: 1px;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 6px 12px;\r\n");
      out.write("            transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control:focus,\r\n");
      out.write("        .border-line:focus {\r\n");
      out.write("            border-color: rgb(170, 143, 211);\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: #e6e6e6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control,\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control::-webkit-input-placeholder {\r\n");
      out.write("            color: #BDBDBD;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container */\r\n");
      out.write("\r\n");
      out.write("        .container-content {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("            padding: 15px 20px 20px 20px;\r\n");
      out.write("            border-color: rgb(170, 143, 211);\r\n");
      out.write("            border-image: none;\r\n");
      out.write("            border-style: solid solid none;\r\n");
      out.write("            border-width: 1px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Backgrounds */\r\n");
      out.write("\r\n");
      out.write("        .main-bg {\r\n");
      out.write("\r\n");
      out.write("            background: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Login & Register Pages*/\r\n");
      out.write("\r\n");
      out.write("        .login-container {\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("            z-index: 100;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding-top: 100px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login.login-container {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrapper.login-container {\r\n");
      out.write("            margin-top: 140px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo-badge {\r\n");
      out.write("            color: rgb(170, 143, 211);\r\n");
      out.write("            font-size: 80px;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            letter-spacing: -10px;\r\n");
      out.write("            margin-bottom: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        *:not(i) {\r\n");
      out.write("            font-family: 'Karla', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navbar-logo>img {\r\n");
      out.write("            padding-top: 0px;\r\n");
      out.write("            padding-bottom: 18px;\r\n");
      out.write("            width: 110px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .loginLogo {\r\n");
      out.write("        	width: 200px;\r\n");
      out.write("            height: 180px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"main-bg\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"login-container text-c  flipInX\" style=\"margin-bottom: 170px; margin-top: 100px;\">\r\n");
      out.write("        <div>\r\n");
      out.write("        	<img src=\"../resources/images/loginLogo.jpg\" class=\"loginLogo\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <h3 class=\"text-whitesmoke\">재능판다에 오신걸 환영해요!</h3>\r\n");
      out.write("        <p class=\"text-whitesmoke\">로그인하기</p>\r\n");
      out.write("        <div class=\"container-content\">\r\n");
      out.write("            <form class=\"margin-t\" action=\"login.do\" method=\"post\" name=\"loginForm\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"text\" name=\"memberId\" class=\"form-control\" onkeyup=\"enterkey();\" placeholder=\"ID 입력\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"password\" name=\"memberPwd\" class=\"form-control\" onkeyup=\"enterkey();\" placeholder=\"*****\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"form-button button-l margin-b\" onclick=\"checklogin();\">로그인</button>\r\n");
      out.write("\r\n");
      out.write("                <a class=\"text-darkyellow\" href=\"/member/findId.do\">아이디 찾기</a>\r\n");
      out.write("                <a class=\"text-darkyellow\" href=\"/member/findPwdForm.do\">비밀번호 찾기</a>\r\n");
      out.write("                <a class=\"text-darkyellow\" href=\"/member/join.do\">회원가입</a>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("          \r\n");
      out.write("       function checklogin() {\r\n");
      out.write("          var form = document.loginForm;\r\n");
      out.write("          \r\n");
      out.write("             if(form.memberId.value == \"\") {\r\n");
      out.write("                alert('아이디를 입력해주세요.');\r\n");
      out.write("                form.memberId.focus();\r\n");
      out.write("                return false;\r\n");
      out.write("             } else if(form.memberPwd.value == \"\") {\r\n");
      out.write("                alert('비밀번호를 입력해주세요.');\r\n");
      out.write("                form.memberPwd.focus();\r\n");
      out.write("                return false;\r\n");
      out.write("             }\r\n");
      out.write("             form.submit();\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       function enterkey() {\r\n");
      out.write("          if (window.event.keyCode == 13) {\r\n");
      out.write("              // 엔터키가 눌렸을 때\r\n");
      out.write("              checklogin();\r\n");
      out.write("           }\r\n");
      out.write("       }\r\n");
      out.write("    </script>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
