/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-26 13:12:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1642957317488L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/myPageSidebar.jsp", Long.valueOf(1642756614000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/footer.jsp", Long.valueOf(1643158528661L));
    _jspx_dependants.put("jar:file:/C:/Last/final-project/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\"/>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("html, body, div, span, applet, object, iframes, h1, h2, h3, h4, h5, h6,\r\n");
      out.write("\r\n");
      out.write("	p, blockquote, pre, a, abbr, acronym, address, big, quotes, code, del,\r\n");
      out.write("\r\n");
      out.write("	dfn, em, img, ins, kbd, q, s, samp, small, strike, sub, sup, tt, var, u,\r\n");
      out.write("\r\n");
      out.write("	i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table,\r\n");
      out.write("\r\n");
      out.write("	caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas,\r\n");
      out.write("\r\n");
      out.write("	details, embed, figure, figcaption, footer, header, hgroup, menu, nav,\r\n");
      out.write("\r\n");
      out.write("	output, ruby, section, summary, time, mark, audio, video {\r\n");
      out.write("\r\n");
      out.write("	margin: 0;\r\n");
      out.write("\r\n");
      out.write("	padding: 0;\r\n");
      out.write("\r\n");
      out.write("	border: 0;\r\n");
      out.write("\r\n");
      out.write("	font-size: 100%;\r\n");
      out.write("\r\n");
      out.write("	do: inherit;\r\n");
      out.write("\r\n");
      out.write("	vertical-align: baseline;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("article, aside, details, figcaption, figure, footer, header, hgroup,\r\n");
      out.write("\r\n");
      out.write("	menu, nav, section {\r\n");
      out.write("\r\n");
      out.write("	display: block;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("blockquote, q {\r\n");
      out.write("\r\n");
      out.write("	quotes: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("blockquote : before, blockquote : after, q : before, q : after {\r\n");
      out.write("\r\n");
      out.write("	content: '';\r\n");
      out.write("\r\n");
      out.write("	content: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("\r\n");
      out.write("	border-spacing: 0;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*css 초기화*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("\r\n");
      out.write("	height: 600px;\r\n");
      out.write("\r\n");
      out.write("	width: 500px;\r\n");
      out.write("\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("\r\n");
      out.write("	margin-left: 30px;\r\n");
      out.write("\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("\r\n");
      out.write("	position: relative;\r\n");
      out.write("\r\n");
      out.write("	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\r\n");
      out.write("\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-header {\r\n");
      out.write("\r\n");
      out.write("	-webkit-transition: 0.5s; /*사파리 & 크롬*/\r\n");
      out.write("\r\n");
      out.write("    -moz-transition: 0.5s;  /*파이어폭스*/\r\n");
      out.write("\r\n");
      out.write("    -ms-transition: 0.5s;	/*인터넷 익스플로러*/\r\n");
      out.write("\r\n");
      out.write("    -o-transition: 0.5s;  /*오페라*/\r\n");
      out.write("\r\n");
      out.write("    transition: 0.5s;\r\n");
      out.write("\r\n");
      out.write("	width: 100%;\r\n");
      out.write("\r\n");
      out.write("	height: 270px;\r\n");
      out.write("\r\n");
      out.write("	border-radius: 15px 15px 0 0;\r\n");
      out.write("\r\n");
      out.write("	background-size: 100% 280px;\r\n");
      out.write("\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card:hover .card-header  {\r\n");
      out.write("\r\n");
      out.write("	opacity: 0.8;\r\n");
      out.write("\r\n");
      out.write("	height: 100px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-header-is_closed{\r\n");
      out.write("\r\n");
      out.write("    background-color: #EF5A31 ;\r\n");
      out.write("\r\n");
      out.write("    color: #FFF ;\r\n");
      out.write("\r\n");
      out.write("    font-weight: bold ;\r\n");
      out.write("\r\n");
      out.write("    text-align: center ;\r\n");
      out.write("\r\n");
      out.write("    float: right;\r\n");
      out.write("\r\n");
      out.write("    margin: 15px 15px 0 0;\r\n");
      out.write("\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("    padding: 10px 10px;\r\n");
      out.write("\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-body {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-body-header{\r\n");
      out.write("\r\n");
      out.write("	line-height: 25px;\r\n");
      out.write("\r\n");
      out.write("	margin: 10px 20px 0px 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-body-description  {\r\n");
      out.write("\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("\r\n");
      out.write("    color: #757B82;\r\n");
      out.write("\r\n");
      out.write("    line-height: 25px;\r\n");
      out.write("\r\n");
      out.write("    -webkit-transition: .2s ease-in-out; /*사파리&크롬*/\r\n");
      out.write("\r\n");
      out.write("    -moz-transition: .2s ease-in-out; /*파이어폭스*/\r\n");
      out.write("\r\n");
      out.write("    -ms-transition: .2s ease-in-out; /*익스플로러*/\r\n");
      out.write("\r\n");
      out.write("    -o-transition: .2s ease-in-out; /*오페라*/\r\n");
      out.write("\r\n");
      out.write("    transition : .2s ease-in-out;\r\n");
      out.write("\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("\r\n");
      out.write("	height: 180px;\r\n");
      out.write("\r\n");
      out.write("	margin: 5px 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card:hover .card-body-description {\r\n");
      out.write("\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("\r\n");
      out.write("    -webkit-transition: .5s ease-in-out;\r\n");
      out.write("\r\n");
      out.write("    -moz-transition: .5s ease-in-out;\r\n");
      out.write("\r\n");
      out.write("    -ms-transition: .5s ease-in-out;\r\n");
      out.write("\r\n");
      out.write("    -o-transition: .5s ease-in-out;\r\n");
      out.write("\r\n");
      out.write("    transition : .5s ease-in-out;\r\n");
      out.write("\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-body-hashtag {\r\n");
      out.write("\r\n");
      out.write("	color: #2478FF;\r\n");
      out.write("\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-body-footer {\r\n");
      out.write("\r\n");
      out.write("  	position: absolute; \r\n");
      out.write("\r\n");
      out.write("  	margin-top: 15px;\r\n");
      out.write("\r\n");
      out.write("  	margin-bottom: 6px;\r\n");
      out.write("\r\n");
      out.write("    bottom: 0; \r\n");
      out.write("\r\n");
      out.write("    width: 314px;\r\n");
      out.write("\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("\r\n");
      out.write("    color: #9FA5A8;\r\n");
      out.write("\r\n");
      out.write("    padding: 0 15px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".icon {\r\n");
      out.write("\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("\r\n");
      out.write("    margin-right: 2px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".icon-view_count {\r\n");
      out.write("\r\n");
      out.write("    width: 25px;\r\n");
      out.write("\r\n");
      out.write("    height: 17px;\r\n");
      out.write("\r\n");
      out.write("	background: url(\"images/eye.jpg\") no-repeat;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".icon-comments_count {\r\n");
      out.write("\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("\r\n");
      out.write("	width: 25px;\r\n");
      out.write("\r\n");
      out.write("    height: 17px;\r\n");
      out.write("\r\n");
      out.write("	background: url(\"images/comment.jpg\") no-repeat;	\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".reg_date {\r\n");
      out.write("\r\n");
      out.write("	float: right;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"header\"></div>\r\n");
      out.write("	<div id=\"includedContent\"></div>\r\n");
      out.write("	<div id=\"content\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
 String contextPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    #content {\r\n");
      out.write("    	height:1000px;\r\n");
      out.write("    }\r\n");
      out.write("    #content>div {\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu {\r\n");
      out.write("        width: 15%;\r\n");
      out.write("        height: 420px;\r\n");
      out.write("        background-color: rgb(170, 143, 211);\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu>ul {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu li {\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu li:hover {\r\n");
      out.write("        background-color: hotpink;\r\n");
      out.write("        cursor : pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("	<div id=\"menu\">\r\n");
      out.write("                <ul class=\"list-group\">\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"myPage();\">개인정보수정</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"tHistory();\">거래내역</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"zzimList();\">관심목록</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"teacherAdd();\">선생신청</li>\r\n");
      out.write("                    <li class=\"list-group-item\" onclick=\"myProfile();\">내 프로필</li>\r\n");
      out.write("                    <li class=\"list-group-item\" data-toggle=\"modal\" data-target=\"#myModal\">계정탈퇴</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("  \r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">정말로 탈퇴 하시겠습니까?</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <!-- Modal body -->\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("         	계정 탈퇴 시 모든 개인정보가 삭제되며\r\n");
      out.write("		구매하신 캐시는 환불되지 않아요\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-danger\" onclick=\"exit()\">탈퇴</button>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	function myPage() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/mypage.do\";\r\n");
      out.write("	}\r\n");
      out.write("	function tHistory() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/thistory.do?currentPage=1\";\r\n");
      out.write("	}\r\n");
      out.write("	function zzimList() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/zzimlist.do?currentPage=1\";\r\n");
      out.write("	}\r\n");
      out.write("	function teacherAdd() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/teacherAdd.do\";\r\n");
      out.write("	}\r\n");
      out.write("	function myProfile() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/myProfile.do\";\r\n");
      out.write("	}\r\n");
      out.write("	function exit() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/exit.do\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"card\">\r\n");
      out.write("		<!-- 카드 헤더 -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>재능판다</title>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 웹 폰트-->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Karla&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("		*:not(i) {\r\n");
      out.write("			font-family: 'Karla', sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<footer class=\"footer-07\" style=\"background-color: rgb(170, 143, 211);\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-12 text-center\">\r\n");
      out.write("					<h2 class=\"footer-heading\" style=\"margin-top:50px;\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"logo\">TalentsellerPanda.com</a></h2>\r\n");
      out.write("		               <p class=\"menu\">\r\n");
      out.write("		                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">재능판다</a>&nbsp;&nbsp;\r\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/footerNotice.do\">공지사항</a>&nbsp;&nbsp;\r\n");
      out.write("					</p>\r\n");
      out.write("					<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("		  <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Twitter\"><span class=\"ion-logo-twitter\"></span></a></li>\r\n");
      out.write("		  <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Facebook\"><span class=\"ion-logo-facebook\"></span></a></li>\r\n");
      out.write("		  <li class=\"ftco-animate\"><a href=\"#\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Instagram\"><span class=\"ion-logo-instagram\"></span></a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-5\">\r\n");
      out.write("				<div class=\"col-md-12 text-center\">\r\n");
      out.write("					<p class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("				  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"ion-ios-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\"  style=\"color: transparent;\">Colorlib.com</a>\r\n");
      out.write("				  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\"\r\n");
      out.write("				stroke=\"#F96D00\" />\r\n");
      out.write("		</svg></div>\r\n");
      out.write("	<script src=\"../resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/c8ea39d107.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("   <script>\r\n");
      out.write("    function fnChkByte(obj, maxByte)\r\n");
      out.write("    {\r\n");
      out.write("        var str = obj.value;\r\n");
      out.write("        var str_len = str.length;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var rbyte = 0;\r\n");
      out.write("        var rlen = 0;\r\n");
      out.write("        var one_char = \"\";\r\n");
      out.write("        var str2 = \"\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        for(var i=0; i<str_len; i++)\r\n");
      out.write("        {\r\n");
      out.write("            one_char = str.charAt(i);\r\n");
      out.write("            if(escape(one_char).length > 4) {\r\n");
      out.write("                rbyte += 2;                                         //한글2Byte\r\n");
      out.write("            }else{\r\n");
      out.write("                rbyte++;                                            //영문 등 나머지 1Byte\r\n");
      out.write("            }\r\n");
      out.write("            if(rbyte <= maxByte){\r\n");
      out.write("                rlen = i+1;                                          //return할 문자열 갯수\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("         if(rbyte > maxByte)\r\n");
      out.write("         {\r\n");
      out.write("            // alert(\"한글 \"+(maxByte/2)+\"자 / 영문 \"+maxByte+\"자를 초과 입력할 수 없습니다.\");\r\n");
      out.write("            alert(\"메세지는 최대 \" + maxByte + \"byte를 초과할 수 없습니다.\")\r\n");
      out.write("            str2 = str.substr(0,rlen);                                  //문자열 자르기\r\n");
      out.write("            obj.value = str2;\r\n");
      out.write("            fnChkByte(obj, maxByte);\r\n");
      out.write("         }\r\n");
      out.write("         else\r\n");
      out.write("         {\r\n");
      out.write("            document.getElementById('byteInfo').innerText = rbyte;\r\n");
      out.write("         }\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function fixProfile() {\r\n");
      out.write("		location.href = \"");
      out.print( contextPath );
      out.write("/member/fixProfile.do\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/myProfile.jsp(346,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sellerList }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<div class=\"card-body-header\">\r\n");
          out.write("			<h3>선생님이 아닙니다.</h3>\r\n");
          out.write("			<h4>선생님 신청을 통해 프로필을 획득 할 수 있습니다.</h4>\r\n");
          out.write("			<button class=\"btn btn-primary\" style=\"background-color:rgb(170, 143, 211); border: 1px soild rgb(170, 143, 211);\" onclick=\"teacherAdd();\">선생님 신청하기</button>\r\n");
          out.write("		</div>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/myProfile.jsp(353,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sellerList && sellerList.get(0).get('ACCEPT_DATE') == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<div class=\"card-body-header\">\r\n");
          out.write("			<h3>선생님 신청 대기중입니다..</h3>\r\n");
          out.write("		</div>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<div class=\"card-header\" style=\"background-image: url(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"FILE_PATH\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(");\">\r\n");
          out.write("\r\n");
          out.write("			<div class = \"card-header-is_closed\" > \r\n");
          out.write("\r\n");
          out.write("                <div class = \"card-header-text\" > ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"GRADE_NAME\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </div > \r\n");
          out.write("\r\n");
          out.write("            </div >\r\n");
          out.write("\r\n");
          out.write("		</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("		<!--  카드 바디 -->\r\n");
          out.write("\r\n");
          out.write("		<div class=\"card-body\">\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("			<!--  카드 바디 헤더 -->\r\n");
          out.write("\r\n");
          out.write("			<div class=\"card-body-header\">\r\n");
          out.write("\r\n");
          out.write("				<p class=\"card-body-hashtag\">#");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"MAINCATEGORY_NAME\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write('#');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"CATEGORY_NAME\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" #경력 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"CAREER\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("년</p>\r\n");
          out.write("\r\n");
          out.write("				 <p class = \"card-body-nickname\"> \r\n");
          out.write("\r\n");
          out.write("                                 닉네임: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"MEMBER_NICK\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\r\n");
          out.write("           		   </p>\r\n");
          out.write("\r\n");
          out.write("			</div>\r\n");
          out.write("\r\n");
          out.write("			<p class=\"card-body-description\">\r\n");
          out.write("				\r\n");
          out.write("				<label for=\"comment\">자기 소개 :</label><br>\r\n");
          out.write("				");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"CONTENTS\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("				\r\n");
          out.write("			</p>\r\n");
          out.write("\r\n");
          out.write("			<!--  카드 바디 본문 -->\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("			<!--  카드 바디 푸터 -->\r\n");
          out.write("\r\n");
          out.write("			<div class=\"card-body-footer\">\r\n");
          out.write("\r\n");
          out.write("				<hr style=\"margin-bottom: 8px; opacity: 0.5; border-color: #EF5A31\">\r\n");
          out.write("\r\n");
          out.write("				허가일 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sellerList.get(0).get(\"ACCEPT_DATE\") }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("				<br>\r\n");
          out.write("				<div align=\"right\">\r\n");
          out.write("			       <button class=\"btn btn-primary\" style=\"background-color:rgb(170, 143, 211); border: 1px soild rgb(170, 143, 211);\" onclick=\"fixProfile();\">프로필 수정</button>\r\n");
          out.write("			    </div>\r\n");
          out.write("			</div>\r\n");
          out.write("\r\n");
          out.write("		</div>\r\n");
          out.write("		<br>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
