/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-26 13:30:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	String contextPath = request.getContextPath();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<title>재능판다</title>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("	<!-- 웹 폰트-->\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Karla&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("	<style>\n");
      out.write("		*:not(i) {\n");
      out.write("			font-family: 'Karla', sans-serif;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		#navbar-logo>img {\n");
      out.write("			padding-top: 0px;\n");
      out.write("			padding-bottom: 18px;\n");
      out.write("			width: 110px;\n");
      out.write("			height: 100px;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		#ftco-navbar {\n");
      out.write("			height: 100px;\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/topbar.jsp", out, false);
      out.write("\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<div id=\"includedContent\"></div>\n");
      out.write("	\n");
      out.write("	<div class=\"hero-wrap js-fullheight\" style=\"background-image: url('../resources/images/main.jpg'); margin-bottom: 50px;\">\n");
      out.write("      <div class=\"overlay\"></div>\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row no-gutters slider-text js-fullheight align-items-center justify-content-start\"\n");
      out.write("            data-scrollax-parent=\"true\">\n");
      out.write("            <div class=\"col-md-9 ftco-animate\" data-scrollax=\" properties: { translateY: '70%' }\">\n");
      out.write("               <h1 class=\"mb-4\" data-scrollax=\"properties: { translateY: '30%', opacity: 1.6 }\"><strong>재능 판다\n");
      out.write("                     <br></strong>숨어있는 당신의 재능</h1>\n");
      out.write("\n");
      out.write("               <p>찾으시는 서비스를 클릭하세요</p>\n");
      out.write("               <p class=\"browse d-md-flex\">\n");
      out.write("                  <span class=\"d-flex justify-content-md-center align-items-md-center\"><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어\"><i\n");
      out.write("                           class=\"fas fa-language\" style=\"color:rgb(170, 143, 211);\"></i>외국어</a></span>\n");
      out.write("                  <span class=\"d-flex justify-content-md-center align-items-md-center\"><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기\"><i\n");
      out.write("                           class=\"fas fa-guitar\" style=\"color:rgb(170, 143, 211);\"></i>악기</a></span>\n");
      out.write("                  <span class=\"d-flex justify-content-md-center align-items-md-center\"><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠\"><i\n");
      out.write("                           class=\"fas fa-running\" style=\"color:rgb(170, 143, 211);\"></i>스포츠</a></span>\n");
      out.write("\n");
      out.write("               </p>\n");
      out.write("               <p class=\"browse d-md-flex\">\n");
      out.write("                  <span class=\"d-flex justify-content-md-center align-items-md-center\"><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미\"><i\n");
      out.write("                           class=\"fas fa-gamepad\" style=\"color:rgb(170, 143, 211);\"></i>취미</a></span>\n");
      out.write("                  <span class=\"d-flex justify-content-md-center align-items-md-center\"><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험/자격증\"><i\n");
      out.write("                           class=\"fas fa-envelope-open-text\"\n");
      out.write("                           style=\"color:rgb(170, 143, 211);\"></i>시험/자격증</a></span>\n");
      out.write("                  <span class=\"d-flex justify-content-md-center align-items-md-center\"><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅\"><i\n");
      out.write("                           class=\"far fa-id-badge\" style=\"color:rgb(170, 143, 211);\"></i>컨설팅</a></span>\n");
      out.write("               </p>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("   <section class=\"ftco-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row justify-content-start mb-5 pb-3\">\n");
      out.write("            <div class=\"col-md-7 heading-section ftco-animate\">\n");
      out.write("               <span class=\"subheading\">인기 서비스</span>\n");
      out.write("               <h2 class=\"mb-4\"><strong>많이 찾으시는</strong> 서비스에요!</h2>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=영어\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/english.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=영어\">영어 레슨</a></h3>\n");
      out.write("                     <hr>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=피아노\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/piano.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=피아노\">피아노 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=피티\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/PT.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=피티\">퍼스널 트레이닝(PT)</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=노래\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/vocal.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=노래\">보컬 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </section>\n");
      out.write("\n");
      out.write("   <section class=\"ftco-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row justify-content-start mb-5 pb-3\">\n");
      out.write("            <div class=\"col-md-7 heading-section ftco-animate\">\n");
      out.write("               <span class=\"subheading\">외국어</span>\n");
      out.write("               <h2 class=\"mb-4\"><strong>실력 Up</strong> 외국어배우기</h2>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=중국어\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/china.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=중국어\">중국어 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=영어\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/english.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=영어\">영어 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=일본어\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/japan.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=일본어\">일본어 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=러시아어\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/russia.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=외국어&categoryName=러시아어\">러시아어 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </section>\n");
      out.write("\n");
      out.write("   <section class=\"ftco-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row justify-content-start mb-5 pb-3\">\n");
      out.write("            <div class=\"col-md-7 heading-section ftco-animate\">\n");
      out.write("               <span class=\"subheading\">악기 서비스</span>\n");
      out.write("               <h2 class=\"mb-4\"><strong>악기 하나 쯤은</strong> 배우고싶어</h2>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=기타\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/guitar.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=기타\">기타 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/piano.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=피아노\">피아노 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/drum.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=드럼\">드럼 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=바이올린\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/violin.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=악기&categoryName=바이올린\">바이올린 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </section>\n");
      out.write("\n");
      out.write("   <section class=\"ftco-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row justify-content-start mb-5 pb-3\">\n");
      out.write("            <div class=\"col-md-7 heading-section ftco-animate\">\n");
      out.write("               <span class=\"subheading\">스포츠 서비스</span>\n");
      out.write("               <h2 class=\"mb-4\"><strong>운동습관</strong> 만들기</h2>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=피티\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/PT.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=피티\">퍼스널 트레이닝(PT)</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=필라테스\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/pilates.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=필라테스\">필라테스 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=수영\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/swim.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=수영\">수영 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=요가\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/yoga.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=스포츠&categoryName=요가\">요가 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </section>\n");
      out.write("\n");
      out.write("   <section class=\"ftco-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row justify-content-start mb-5 pb-3\">\n");
      out.write("            <div class=\"col-md-7 heading-section ftco-animate\">\n");
      out.write("               <span class=\"subheading\">취미 서비스</span>\n");
      out.write("               <h2 class=\"mb-4\"><strong>취미,</strong> 더 깊게 즐겨요</h2>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=요리\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/cook.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=요리\">요리 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=노래\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/vocal.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=노래\">보컬 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=게임\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/game.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=게임\">게임 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=미술\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/art.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=취미&categoryName=미술\">미술 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </section>\n");
      out.write("\n");
      out.write("   <section class=\"ftco-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row justify-content-start mb-5 pb-3\">\n");
      out.write("            <div class=\"col-md-7 heading-section ftco-animate\">\n");
      out.write("               <span class=\"subheading\">시험/자격증 서비스</span>\n");
      out.write("               <h2 class=\"mb-4\"><strong>시험,자격증 </strong> 전문가가 도와드려요</h2>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=공무원\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/public.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=공무원\">공무원 시험</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=세무사\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/tax.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=세무사\">세무사 시험</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=공인중개사\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/realtor.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=공인중개사\">공인중개사 시험</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=사회복지사\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/social.png);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=시험%2F자격증&categoryName=사회복지사\">사회복지사 시험</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </section>\n");
      out.write("\n");
      out.write("   <section class=\"ftco-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"row justify-content-start mb-5 pb-3\">\n");
      out.write("            <div class=\"col-md-7 heading-section ftco-animate\">\n");
      out.write("               <span class=\"subheading\">컨설팅 서비스</span>\n");
      out.write("               <h2 class=\"mb-4\"><strong>컨설팅,</strong> 함께 하면 어렵지 않아요</h2>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=대학입시 컨설팅\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/university.png);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=대학입시 컨설팅\">대학 입시 컨설팅</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=면접\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/meeting.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=면접\">면접 레슨</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=포트폴리오\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/portpolio.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=포트폴리오\">포트폴리오 컨설팅</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 col-lg-3 ftco-animate\">\n");
      out.write("               <div class=\"destination\">\n");
      out.write("                  <a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=대학원\" class=\"img img-2 d-flex justify-content-center align-items-center\"\n");
      out.write("                     style=\"background-image: url(../resources/images/graduate.jpg);\">\n");
      out.write("                     <div class=\"icon d-flex justify-content-center align-items-center\">\n");
      out.write("                        <span class=\"icon-search2\"></span>\n");
      out.write("                     </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"text p-3\">\n");
      out.write("                     <h3><a href=\"/board/categoryBoard.do?currentPage=1&mainCategory=컨설팅&categoryName=대학원\">대학원 컨설팅</a></h3>\n");
      out.write("                  </div>\n");
      out.write("               </div>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </section>\n");
      out.write("\n");
      out.write("	<!-- 푸터바 인클루드 예정 -->\n");
      out.write("	\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
