/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-24 10:16:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class box_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1642957317488L));
    _jspx_dependants.put("jar:file:/C:/Last/final-project/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>채팅함</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("@import url(https://fonts.googleapis.com/earlyaccess/notosanskr.css);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("	font-family: 'Noto Sans KR' !important;\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	font-size: 20px !important;\r\n");
      out.write("}	\r\n");
      out.write("\r\n");
      out.write("h5 {\r\n");
      out.write("	font-family: 'Noto Sans KR' !important;\r\n");
      out.write("	font-size: 15px !important;\r\n");
      out.write("}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		*:not(i) {\r\n");
      out.write("			font-family: 'Karla', sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#navbar-logo>img {\r\n");
      out.write("			padding-top: 0px;\r\n");
      out.write("			padding-bottom: 18px;\r\n");
      out.write("			width: 110px;\r\n");
      out.write("			height: 100px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#ftco-navbar {\r\n");
      out.write("			height: 100px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	/* 테이블 관련 디자인 처리 */\r\n");
      out.write("	\r\n");
      out.write("#table-test th{\r\n");
      out.write("	position: sticky;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("}	\r\n");
      out.write("	\r\n");
      out.write("thead th {\r\n");
      out.write("	background-color: rgb(170, 143, 211); ;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("tr td:first-child,\r\n");
      out.write("tr th:first-child {\r\n");
      out.write("	border-top-left-radius: 6px;\r\n");
      out.write("	border-bottom-left-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("tr td:last-child,\r\n");
      out.write("tr th:last-child {\r\n");
      out.write("	border-top-right-radius: 6px;\r\n");
      out.write("	border-bottom-right-radius: 6px;\r\n");
      out.write("}	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" /* 안읽은 메세지 */ \r\n");
      out.write(" 	.count {\r\n");
      out.write("		  display: inline;\r\n");
      out.write("		  padding: .2em .6em .3em;\r\n");
      out.write("		  font-size: 75%;\r\n");
      out.write("		  font-weight: bold;\r\n");
      out.write("		  line-height: 1;\r\n");
      out.write("		  color: #fff;\r\n");
      out.write("		  text-align: center;\r\n");
      out.write("		  white-space: nowrap;\r\n");
      out.write("		  vertical-align: baseline;\r\n");
      out.write("		  border-radius: .20em;\r\n");
      out.write("		  position: relative;\r\n");
      out.write(" 		  top: -1px;\r\n");
      out.write("}\r\n");
      out.write("		\r\n");
      out.write("		 .count-info {\r\n");
      out.write("		  background-color: rgb(170, 143, 211);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		.count:empty {\r\n");
      out.write("		 display:none !important;\r\n");
      out.write("		}\r\n");
      out.write(" 		\r\n");
      out.write("		/* 헤더 안읽은 메세지 */ \r\n");
      out.write(" 	\r\n");
      out.write("		.headercount:empty {\r\n");
      out.write("		 display:none !important;\r\n");
      out.write("		}\r\n");
      out.write(" 		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	/* 채팅박스단 */\r\n");
      out.write("		\r\n");
      out.write(".img-circle {\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".media-object {\r\n");
      out.write("  display: block !important; \r\n");
      out.write("  max-width: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pull-right {\r\n");
      out.write("  float: right !important;\r\n");
      out.write("}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/topbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <br><br><br><br><br>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\" style=\"margin: 0 auto; width:800px; height:800px; overflow:auto;\">\r\n");
      out.write("        <table class=\"table\" id=\"table-test\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th><h4>채팅</h4></th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <div style=\"overflow-y: auto; width: 100%; max-height: 450px;\">\r\n");
      out.write("                <table class=\"table table-bordered table-hover\" style=\"text-align: center; border: 1px solid #dddddd; margin: 0 auto;\">\r\n");
      out.write("                    <tbody id=\"boxTable\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("	boxListFunction();\r\n");
      out.write("	getUnread();})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function boxListFunction() {\r\n");
      out.write("\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type: \"POST\",\r\n");
      out.write("		url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/test/test3.do\",\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		success: function(result) {\r\n");
      out.write("			console.log(result);\r\n");
      out.write("			console.log(\"ajax 성공\");\r\n");
      out.write("			\r\n");
      out.write("			var str = \"\";  \r\n");
      out.write("			for(var i=0; i<result.length; i++) {\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				if(result[i].fromNick == '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.memberNick }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' ) {\r\n");
      out.write("					\r\n");
      out.write("					 str += '<tr onclick=\"location.href=\\'chat.me?currentPage=1&toNick='+result[i].toNick + '\\'\">' +\r\n");
      out.write("		    			'<td style=\"width: 150px;\">' + \r\n");
      out.write("		    			'<img class=\"media-object img-circle\" style=\"margin: 0 auto; max-width: 40px; max-height: 40px;\" src=\"../resources/images/icon.png\">' +                       \r\n");
      out.write("		    			'<h5>' + result[i].toNick +'</h5></td>' +\r\n");
      out.write("		    			'<td>' +\r\n");
      out.write("		    			'<h5>' + result[i].chatContent +\r\n");
      out.write("		    			'<span class=\"count count-info\">' + result[i].chatCount +'</span></h5>' + \r\n");
      out.write("		    			'<div class=\"pull-right\">' + result[i].chatTime + '</div>' + \r\n");
      out.write("		    			'</td>' + \r\n");
      out.write("		    			'</tr>'\r\n");
      out.write("				} else {\r\n");
      out.write("					 str += '<tr onclick=\"location.href=\\'chat.me?currentPage=1&toNick=' + result[i].fromNick + '\\'\">' +\r\n");
      out.write("		    			'<td style=\"width: 150px;\">' + \r\n");
      out.write("		    			'<img class=\"media-object img-circle\" style=\"margin: 0 auto; max-width: 40px; max-height: 40px;\" src=\"../resources/images/icon.png\">' +                       \r\n");
      out.write("		    			'<h5>' + result[i].fromNick +'</h5></td>' + \r\n");
      out.write("		    			'<td>' +\r\n");
      out.write("		    			'<h5>' + result[i].chatContent +\r\n");
      out.write("		    			'<span class=\"count count-info\">' + result[i].chatCount +  '</span></h5>' + \r\n");
      out.write("		    			'<div class=\"pull-right\">' + result[i].chatTime + '</div>' + \r\n");
      out.write("		    			'</td>' + \r\n");
      out.write("		    			'</tr>'\r\n");
      out.write("				} \r\n");
      out.write("			}	\r\n");
      out.write("			$('#boxTable').html(str);\r\n");
      out.write("			 \r\n");
      out.write("			},\r\n");
      out.write("			\r\n");
      out.write("		error : function() {\r\n");
      out.write("  				console.log(\"ajax 실패\");\r\n");
      out.write("  			}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getUnread() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type: \"post\",\r\n");
      out.write("		url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/test/test4.do\",\r\n");
      out.write("		\r\n");
      out.write("		success: function(result) {\r\n");
      out.write("			if(result >= 1) {\r\n");
      out.write("				$('#unread').html(result);\r\n");
      out.write("			} else {\r\n");
      out.write("				$('#unread').html('');\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		\r\n");
      out.write("		error : function() {\r\n");
      out.write("				console.log(\"ajax 실패\");\r\n");
      out.write("			}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
